### PR TITLE
Templates

### PR DESCRIPTION
**Pull request by drymek**
I've made only 2 little changes:
#1. check first local templates, than global (templates order).
#2. Check templates in server directory (targetDir) not in tmp (buildDir)

for both: pirum.css and index.html

### CODE REVIEW

**Comment by kukulich** [comment]
Yes, the local templates don't work because of using buildDir instead of targetDir.

**Comment by kukulich** [comment]
Is there any reason why this pull request has not been merged? Thanks.

**Comment by elkuku** [comment]
I was about to submit the same pull request...
Please merge ;)

**Comment by llaville** [comment]
Hello,

I know that templating customization is a real need. Two months ago, I've opened mysel a request about it 
https://github.com/fabpot/Pirum/pull/43

Now, I've closed it because I provide an alternative solution to patch Pirum.

I've named this solution Pirus, and it's available at http://php5.laurent-laville.org/pirus/

Feel free to comment.

**Comment by fabpot** [comment]
Closing as Pirum is now deprecated, and not maintained anymore.

**Pull request closed without merging**
