### PR TITLE
Setup auto-discovery of dependencies

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@fabpot - bump :-)

**Comment by fabpot** [comment]
I don't see the added value. If you set the auto-discovering, then you should use the server host name when installing a library for the first time, instead of the shortcut. But then, for the next ones, the shortcut will work. So, this is probably more confusion than anything on the generated page. That being said, it is a nice setting that should probably be set to one by default in PEAR.

**Comment by ghost** [comment]
My ow experiences using PEAR was that the dependencies were always a pain until I discovered this particular setting.  All we're doing here is giving some suggestion on the instruction page which makes it more easy for the user.

**Comment by fabpot** [comment]
In this case, it should be a mentioned as a tip, and should be mentioned elsewhere in the page.

**Comment by ghost** [comment]
@fabpot Do you mean something like this? https://github.com/drak/Pirum/compare/autodiscover

**Comment by ghost** [comment]
I'd also like to point out, I only discovered the setting when I first setup PHPUnit, see http://www.phpunit.de/manual/current/en/installation.html

**Comment by ghost** [comment]
@fabpot, or maybe the better way is to consider something like #43

**Pull request closed without merging**
